language: perl

matrix:
  include:
  - perl: "5.30"
  - perl: "5.26"
  - perl: "5.22"
  - perl: "5.20"
    dist: trusty
  - perl: "5.16"
    dist: trusty

sudo: false

notifications:
  email: false

before_install:
  - cpanm --installdeps -n -q .
  - cpanm -n -q Devel::Cover Devel::Cover::Report::Coveralls

after_success:
  - cover -report coveralls

addons:
  apt:
    packages:
    - gfortran
